/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "login": [],
    "account.edit": [],
    "account.update": [],
    "folder.store": [],
    "folder.update": [
        {
            "name": "folder",
            "required": true
        }
    ],
    "media": [],
    "all": [],
    "text": [],
    "view": [
        {
            "name": "file",
            "required": true
        }
    ],
    "upload": [],
    "storage.local": [
        {
            "name": "path",
            "required": true
        }
    ]
}
}
export {};
