import hljs from "highlight.js";
import "highlight.js/styles/github.css";
import { useEffect, useRef } from "react";

const languageMap = {
    "1c": "1C",
    "4d": "4D",
    abnf: "ABNF",
    ada: "Ada",
    apex: "Apex",
    arduino: "Arduino",
    ino: "Arduino",
    actionscript: "ActionScript",
    as: "ActionScript",
    ln: "Alan",
    angelscript: "AngelScript",
    asc: "AngelScript",
    apache: "Apache",
    apacheconf: "Apache",
    applescript: "AppleScript",
    osascript: "AppleScript",
    arcade: "Arcade",
    asciidoc: "AsciiDoc",
    adoc: "AsciiDoc",
    aspectj: "AspectJ",
    autohotkey: "AutoHotkey",
    autoit: "AutoIt",
    awk: "Awk",
    mawk: "Awk",
    nawk: "Awk",
    gawk: "Awk",
    bash: "Bash",
    sh: "Bash",
    zsh: "Bash",
    basic: "Basic",
    bbcode: "BBCode",
    blade: "Blade",
    bnf: "BNF",
    brainfuck: "Brainfuck",
    bf: "Brainfuck",
    csharp: "C#",
    cs: "C#",
    c: "C",
    h: "C",
    cpp: "C++",
    hpp: "C++",
    cc: "C++",
    hh: "C++",
    cxx: "C++",
    hxx: "C++",
    cmake: "CMake",
    "cmake.in": "CMake",
    css: "CSS",
    coq: "Coq",
    csp: "CSP",
    d: "D",
    dart: "Dart",
    diff: "Diff",
    patch: "Diff",
    dockerfile: "Dockerfile",
    docker: "Dockerfile",
    dos: "DOS",
    bat: "DOS",
    cmd: "DOS",
    ebnf: "EBNF",
    elixir: "Elixir",
    elm: "Elm",
    erlang: "Erlang",
    erl: "Erlang",
    fsharp: "F#",
    fs: "F#",
    fsx: "F#",
    fsi: "F#",
    fsscript: "F#",
    gcode: "G-Code",
    nc: "G-Code",
    go: "Go",
    golang: "Go",
    gradle: "Gradle",
    graphql: "GraphQL",
    gql: "GraphQL",
    groovy: "Groovy",
    html: "HTML",
    xml: "HTML",
    xhtml: "HTML",
    rss: "XML",
    atom: "XML",
    xjb: "XML",
    xsd: "XML",
    xsl: "XML",
    plist: "XML",
    svg: "XML",
    http: "HTTP",
    https: "HTTP",
    ini: "Ini",
    toml: "TOML",
    json: "JSON",
    jsonc: "JSON",
    java: "Java",
    jsp: "Java",
    javascript: "JavaScript",
    js: "JavaScript",
    jsx: "JavaScript",
    julia: "Julia",
    jl: "Julia",
    kotlin: "Kotlin",
    kt: "Kotlin",
    latex: "LaTeX",
    tex: "LaTeX",
    less: "Less",
    lisp: "Lisp",
    lua: "Lua",
    markdown: "Markdown",
    md: "Markdown",
    mkdown: "Markdown",
    mkd: "Markdown",
    matlab: "Matlab",
    nginx: "Nginx",
    nginxconf: "Nginx",
    nim: "Nim",
    nix: "Nix",
    perl: "Perl",
    pl: "Perl",
    pm: "Perl",
    php: "PHP",
    powershell: "PowerShell",
    ps: "PowerShell",
    ps1: "PowerShell",
    processing: "Processing",
    prolog: "Prolog",
    properties: "Properties",
    puppet: "Puppet",
    pp: "Puppet",
    python: "Python",
    py: "Python",
    gyp: "Python",
    r: "R",
    ruby: "Ruby",
    rb: "Ruby",
    rust: "Rust",
    rs: "Rust",
    scss: "SCSS",
    sql: "SQL",
    scala: "Scala",
    shell: "Shell",
    swift: "Swift",
    typescript: "TypeScript",
    ts: "TypeScript",
    tsx: "TypeScript",
    yaml: "YAML",
    yml: "YAML",
    zig: "Zig",
};

export default function AutoHighlight({
    code,
    ext,
}: {
    code: string;
    ext: string;
}) {
    const codeRef = useRef<HTMLElement>(null);

    useEffect(() => {
        if (codeRef.current) {
            let highlighted: string;
            if (ext in languageMap) {
                highlighted = hljs.highlight(code, {
                    language: languageMap[ext as keyof typeof languageMap],
                }).value;
            } else {
                highlighted = hljs.highlightAuto(code).value;
            }

            codeRef.current.innerHTML = highlighted;
        }
    }, [code]);

    return (
        <pre>
            <code ref={codeRef}>{code}</code>
        </pre>
    );
}
